"""Plugin type keys, diagnostic codes, and rejection helpers."""

from __future__ import annotations

from rextio.analyzer.diagnostics import Diagnostic
from rextio.plugins.api import ClaimSite, Rejected

PLUGIN_ID = "rextio-torch"

TENSOR_F32_CPU_1D = "rextio-torch/tensor-f32-cpu-1d"
TENSOR_F32_CPU_2D = "rextio-torch/tensor-f32-cpu-2d"
TENSOR_I64_CPU_1D = "rextio-torch/tensor-i64-cpu-1d"
TENSOR_F32_CUDA0_1D = "rextio-torch/tensor-f32-cuda0-1d"
TENSOR_F32_CUDA0_2D = "rextio-torch/tensor-f32-cuda0-2d"

TENSOR_TYPE_KEYS: frozenset[str] = frozenset(
    {
        TENSOR_F32_CPU_1D,
        TENSOR_F32_CPU_2D,
        TENSOR_I64_CPU_1D,
        TENSOR_F32_CUDA0_1D,
        TENSOR_F32_CUDA0_2D,
    }
)

# type key -> (dtype token, device token, rank)
_TENSOR_META: dict[str, tuple[str, str, int]] = {
    TENSOR_F32_CPU_1D: ("f32", "cpu", 1),
    TENSOR_F32_CPU_2D: ("f32", "cpu", 2),
    TENSOR_I64_CPU_1D: ("i64", "cpu", 1),
    TENSOR_F32_CUDA0_1D: ("f32", "cuda:0", 1),
    TENSOR_F32_CUDA0_2D: ("f32", "cuda:0", 2),
}

# Per-rule diagnostic codes (must be unique across RuleRecord entries).
DIAGNOSTIC_LINEAR = "RXTP-TORCH-001"
DIAGNOSTIC_RELU = "RXTP-TORCH-002"  # rank-2 ReLU (Phase A certified)
DIAGNOSTIC_MEAN = "RXTP-TORCH-003"
DIAGNOSTIC_RELU_1D = "RXTP-TORCH-004"
DIAGNOSTIC_SIGMOID_1D = "RXTP-TORCH-005"
DIAGNOSTIC_SIGMOID_2D = "RXTP-TORCH-006"
DIAGNOSTIC_TANH_1D = "RXTP-TORCH-007"
DIAGNOSTIC_TANH_2D = "RXTP-TORCH-008"
DIAGNOSTIC_MATMUL = "RXTP-TORCH-009"  # binary @ form
DIAGNOSTIC_UNSUPPORTED = "RXTP-TORCH-010"
DIAGNOSTIC_ADD_SAME_RANK = "RXTP-TORCH-011"
DIAGNOSTIC_ADD_BROADCAST = "RXTP-TORCH-012"
DIAGNOSTIC_SUM = "RXTP-TORCH-013"
DIAGNOSTIC_MATMUL_CALL = "RXTP-TORCH-014"
DIAGNOSTIC_SOFTMAX = "RXTP-TORCH-015"
DIAGNOSTIC_ARGMAX = "RXTP-TORCH-016"
DIAGNOSTIC_MUL_SAME_RANK = "RXTP-TORCH-017"
DIAGNOSTIC_MUL_BROADCAST = "RXTP-TORCH-018"
DIAGNOSTIC_SUB_SAME_RANK = "RXTP-TORCH-019"
DIAGNOSTIC_SUB_BROADCAST = "RXTP-TORCH-020"
DIAGNOSTIC_DIV_SAME_RANK = "RXTP-TORCH-021"
DIAGNOSTIC_DIV_BROADCAST = "RXTP-TORCH-022"
DIAGNOSTIC_LINEAR_NO_BIAS = "RXTP-TORCH-023"
DIAGNOSTIC_FUNCTION_RELU = "RXTP-TORCH-024"
DIAGNOSTIC_FUNCTION_SIGMOID = "RXTP-TORCH-025"
DIAGNOSTIC_FUNCTION_TANH = "RXTP-TORCH-026"
DIAGNOSTIC_MEAN_STATIC = "RXTP-TORCH-027"
DIAGNOSTIC_SUM_STATIC = "RXTP-TORCH-028"
DIAGNOSTIC_SOFTMAX_STATIC = "RXTP-TORCH-029"
DIAGNOSTIC_ARGMAX_STATIC = "RXTP-TORCH-030"
DIAGNOSTIC_FUNCTION_ADD = "RXTP-TORCH-031"
DIAGNOSTIC_FUNCTION_SUB = "RXTP-TORCH-032"
DIAGNOSTIC_FUNCTION_MUL = "RXTP-TORCH-033"
DIAGNOSTIC_FUNCTION_DIV = "RXTP-TORCH-034"
DIAGNOSTIC_MATMUL_MIXED_RANK = "RXTP-TORCH-035"
DIAGNOSTIC_MATMUL_CALL_MIXED_RANK = "RXTP-TORCH-036"
DIAGNOSTIC_UNARY_ABS = "RXTP-TORCH-037"
DIAGNOSTIC_UNARY_NEG = "RXTP-TORCH-038"
DIAGNOSTIC_UNARY_NEGATIVE = "RXTP-TORCH-039"
DIAGNOSTIC_UNARY_SQUARE = "RXTP-TORCH-040"
DIAGNOSTIC_UNARY_EXP = "RXTP-TORCH-041"
DIAGNOSTIC_UNARY_LOG = "RXTP-TORCH-042"
DIAGNOSTIC_UNARY_SQRT = "RXTP-TORCH-043"
DIAGNOSTIC_GELU_NONE = "RXTP-TORCH-044"
DIAGNOSTIC_CUDA_MATMUL = "RXTP-TORCH-045"
DIAGNOSTIC_CUDA_BIAS_ADD = "RXTP-TORCH-046"
DIAGNOSTIC_CUDA_RELU = "RXTP-TORCH-047"
DIAGNOSTIC_CUDA_MEAN = "RXTP-TORCH-048"
DIAGNOSTIC_CUDA_E2 = "RXTP-TORCH-049"

# Shared claim-time family codes for activation/binop shape rejections.
DIAGNOSTIC_SIGMOID = DIAGNOSTIC_SIGMOID_2D
DIAGNOSTIC_TANH = DIAGNOSTIC_TANH_2D
DIAGNOSTIC_ADD = DIAGNOSTIC_ADD_SAME_RANK
DIAGNOSTIC_MUL = DIAGNOSTIC_MUL_SAME_RANK
DIAGNOSTIC_SUB = DIAGNOSTIC_SUB_SAME_RANK
DIAGNOSTIC_DIV = DIAGNOSTIC_DIV_SAME_RANK

RUNTIME_ERRORS = {
    "not_tensor": "rextio-torch: expected a torch.Tensor",
    "device": "rextio-torch: expected a CPU tensor",
    "dtype": "rextio-torch: expected a float32 tensor",
    "rank": "rextio-torch: tensor rank does not match the annotated type",
}


def tensor_meta(type_key: str) -> tuple[str, str, int] | None:
    """Return ``(dtype, device, rank)`` for a plugin tensor key, else None."""
    return _TENSOR_META.get(type_key)


def is_tensor_type(type_key: str | None) -> bool:
    """Report whether ``type_key`` is one of this plugin's tensor types."""
    return type_key is not None and type_key in TENSOR_TYPE_KEYS


def reject(site: ClaimSite, code: str, message: str, suggestion: str) -> Rejected:
    """Build a location-neutral plugin rejection; core stamps the source site."""
    return Rejected(
        diagnostic=Diagnostic(
            code=code,
            severity="error",
            message=f"rextio-torch cannot lower {site.target!r}: {message}",
            file_path="",
            line=0,
            column=0,
            suggestion=suggestion,
        )
    )


__all__ = [
    "DIAGNOSTIC_ADD",
    "DIAGNOSTIC_ADD_BROADCAST",
    "DIAGNOSTIC_ADD_SAME_RANK",
    "DIAGNOSTIC_CUDA_BIAS_ADD",
    "DIAGNOSTIC_CUDA_E2",
    "DIAGNOSTIC_CUDA_MATMUL",
    "DIAGNOSTIC_CUDA_MEAN",
    "DIAGNOSTIC_CUDA_RELU",
    "DIAGNOSTIC_LINEAR",
    "DIAGNOSTIC_LINEAR_NO_BIAS",
    "DIAGNOSTIC_MATMUL",
    "DIAGNOSTIC_MATMUL_CALL",
    "DIAGNOSTIC_MATMUL_CALL_MIXED_RANK",
    "DIAGNOSTIC_MATMUL_MIXED_RANK",
    "DIAGNOSTIC_MEAN",
    "DIAGNOSTIC_MEAN_STATIC",
    "DIAGNOSTIC_DIV",
    "DIAGNOSTIC_DIV_BROADCAST",
    "DIAGNOSTIC_DIV_SAME_RANK",
    "DIAGNOSTIC_MUL",
    "DIAGNOSTIC_MUL_BROADCAST",
    "DIAGNOSTIC_MUL_SAME_RANK",
    "DIAGNOSTIC_RELU",
    "DIAGNOSTIC_RELU_1D",
    "DIAGNOSTIC_FUNCTION_RELU",
    "DIAGNOSTIC_FUNCTION_ADD",
    "DIAGNOSTIC_FUNCTION_DIV",
    "DIAGNOSTIC_FUNCTION_MUL",
    "DIAGNOSTIC_FUNCTION_SIGMOID",
    "DIAGNOSTIC_FUNCTION_SUB",
    "DIAGNOSTIC_FUNCTION_TANH",
    "DIAGNOSTIC_GELU_NONE",
    "DIAGNOSTIC_SIGMOID",
    "DIAGNOSTIC_SIGMOID_1D",
    "DIAGNOSTIC_SIGMOID_2D",
    "DIAGNOSTIC_SOFTMAX",
    "DIAGNOSTIC_SOFTMAX_STATIC",
    "DIAGNOSTIC_SUM",
    "DIAGNOSTIC_SUM_STATIC",
    "DIAGNOSTIC_SUB",
    "DIAGNOSTIC_SUB_BROADCAST",
    "DIAGNOSTIC_SUB_SAME_RANK",
    "DIAGNOSTIC_TANH",
    "DIAGNOSTIC_TANH_1D",
    "DIAGNOSTIC_TANH_2D",
    "DIAGNOSTIC_UNSUPPORTED",
    "DIAGNOSTIC_UNARY_ABS",
    "DIAGNOSTIC_UNARY_EXP",
    "DIAGNOSTIC_UNARY_LOG",
    "DIAGNOSTIC_UNARY_NEG",
    "DIAGNOSTIC_UNARY_NEGATIVE",
    "DIAGNOSTIC_UNARY_SQRT",
    "DIAGNOSTIC_UNARY_SQUARE",
    "DIAGNOSTIC_ARGMAX",
    "DIAGNOSTIC_ARGMAX_STATIC",
    "PLUGIN_ID",
    "RUNTIME_ERRORS",
    "TENSOR_F32_CPU_1D",
    "TENSOR_F32_CPU_2D",
    "TENSOR_F32_CUDA0_1D",
    "TENSOR_F32_CUDA0_2D",
    "TENSOR_I64_CPU_1D",
    "TENSOR_TYPE_KEYS",
    "is_tensor_type",
    "reject",
    "tensor_meta",
]
